version: '3'
services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    expose:
      - "3000"
    networks:
      - frontend_network

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    command: bash /opt/app/conf/bootstrap_nginx.sh
    volumes:
      - ./conf:/opt/app/conf
    ports:
      - 80:80
    networks:
      - frontend_network
    depends_on:
      - frontend

networks:
  frontend_network:
    driver: bridge
