name: Deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  


jobs:
  deploy:
    name: Deploy to gcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo $GITHUB_RUN_ID
      - run: envsubst < deployment-frontend.yml > deployment-frontend-feed.yml
      - run: cat deployment-frontend.yml
      - run: cat deployment-frontend-feed.yml
      - name: Deploy frontend
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: europe-west1-b
        with:
          args: apply -f ./deployment-frontend.yml
      - name: Deploy ingress
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: europe-west1-b
        with:
          args: apply -f ./deployment-ingress.yml
      
