name: Deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  


jobs:
  deploy:
    name: Deploy to gcp
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: europe-west1-b
        with:
          args: apply -f deployment-frontend.yaml
      