name: Build and Publish Docker image
on:
  push:
    branches: master

jobs:
  build_and_push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_IMAGES_PAT }}
          registry: docker.pkg.github.com
          repository: Syndorik/WebsiteResume/frontend
          image-name: frontend 
          dockerfile: ./resumeFrontend/Dockerfile
          tag_with_ref: true
