name: Build and Publish Docker image
on:
  push:
    branches: main
    paths-ignore: .github/**
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  


jobs:
  build_and_push_to_registry_deploy:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_IMAGES_PAT }}
          registry: docker.pkg.github.com
          build_args: PROJECT_PATH=./resumeFrontend
          dockerfile: ./resumeFrontend/Dockerfile
          repository: syndorik/websiteresume/frontend
          tag_with_ref: true
      - name: Deploy frontend
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: europe-west1-b
        with:
          args: apply -f deployment-frontend.yaml

  
